const $=s=>document.querySelector(s);
const quests=[
 {title:'The First Days',chapter:'Creation',reference:'Genesis 1:1–31',icon:'☀',kind:'creation',intro:'God made the heavens and the earth. Put the six days of Creation in order.'},
 {title:'Two by Two',chapter:'Noah',reference:'Genesis 6:19–20',icon:'🐘',kind:'pairs',intro:'Noah brought living creatures into the ark. Find each animal’s match.'},
 {title:'A Promise in the Sky',chapter:'Noah',reference:'Genesis 9:12–17',icon:'🌈',kind:'rainbow',intro:'The rainbow reminds us of God’s covenant. Watch the colors, then repeat the pattern.'},
 {title:'Courage in the Valley',chapter:'David',reference:'1 Samuel 17:45–50',icon:'✦',kind:'sling',intro:'David faced Goliath trusting the Lord. Time your sling as the marker crosses the center.'},
 {title:'The One Who Was Lost',chapter:'Jesus',reference:'Luke 15:3–7',icon:'🐑',kind:'sheep',intro:'The shepherd goes after the one lost sheep. Find a path through the hills.'}
];
const creation=[['Light','☀'],['Sky','☁'],['Land & plants','🌿'],['Sun, moon & stars','🌙'],['Fish & birds','🐟'],['Animals & people','🐾']];
const animalIcons=['🐘','🦒','🦓','🐑','🐦','🐢'];
const colors=[['Red','#ee5a59'],['Orange','#fa9c4b'],['Yellow','#f6cf58'],['Green','#5fbf82'],['Blue','#4d9bd3']];
const saved=(()=>{try{return JSON.parse(localStorage.getItem('bibleQuestSave')||'{}')}catch{return{}}})();
const state={unlocked:Math.min(5,Math.max(0,Number(saved.unlocked)||0)),best:Array.isArray(saved.best)?saved.best:[],sound:false,view:'map',level:Math.min(4,Math.max(0,Number(saved.unlocked)||0)),round:null};
let slingTimer=null;let rainbowTimers=[];
function save(){localStorage.setItem('bibleQuestSave',JSON.stringify({unlocked:state.unlocked,best:state.best}))}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function message(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(message.timer);message.timer=setTimeout(()=>t.classList.remove('show'),2500)}
function tone(freq=520){if(!state.sound)return;try{const C=window.AudioContext||window.webkitAudioContext;const ctx=new C(),o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.value=freq;g.gain.value=.075;o.connect(g).connect(ctx.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.16);o.stop(ctx.currentTime+.17);setTimeout(()=>ctx.close(),350)}catch{}}
function stopActivity(){if(slingTimer){cancelAnimationFrame(slingTimer);slingTimer=null}rainbowTimers.forEach(clearTimeout);rainbowTimers=[]}
function header(){ $('#progress-label').textContent=`${state.unlocked} of ${quests.length} quests`;$('#sound').textContent=state.sound?'♫':'♪';$('#sound').setAttribute('aria-label',state.sound?'Turn sound off':'Turn sound on')}
function showMap(){stopActivity();state.view='map';header();$('#app').innerHTML=`<section class="map"><div class="map-art"><img src="assets/story-map.png" alt="Illustrated journey from Creation to the ark and David’s hillside" width="1672" height="941"><div class="map-title"><span>STORY ADVENTURE</span><h1>Choose your next quest.</h1></div></div><div class="map-inner"><p class="map-intro">Explore the story, solve a challenge, and discover what God’s Word says.</p><div class="quest-list">${quests.map((q,i)=>`<button class="quest-card ${i>state.unlocked?'locked':''}" data-level="${i}" ${i>state.unlocked?'disabled':''}><span class="quest-icon">${q.icon}</span><span class="quest-copy"><small>${q.chapter.toUpperCase()} · QUEST ${i+1}</small><strong>${q.title}</strong><em>${q.reference}</em></span><span class="quest-status">${i<state.unlocked?'✓':i===state.unlocked?'PLAY':'🔒'}</span></button>`).join('')}</div><div class="grace-note"><b>The best news is free.</b> You can earn stars in this game, but you cannot earn God’s love. Salvation is His gift through faith in Jesus. <span>Ephesians 2:8–9</span></div></div></section>`}
function startLevel(i){if(i>state.unlocked)return;stopActivity();state.level=i;state.view='intro';const q=quests[i];$('#app').innerHTML=`<section class="play-shell"><button class="back" data-map>← Quest map</button><div class="level-heading"><span>${q.chapter.toUpperCase()} · QUEST ${i+1} OF ${quests.length}</span><h1>${q.icon} ${q.title}</h1><p>${q.intro}</p><b>${q.reference}</b></div><button class="primary" data-begin>Start challenge <span>→</span></button></section>`}
function begin(){const kind=quests[state.level].kind;state.view='play';if(kind==='creation')initCreation();if(kind==='pairs')initPairs();if(kind==='rainbow')initRainbow();if(kind==='sling')initSling();if(kind==='sheep')initSheep()}
function frame(title,instructions,content){$('#app').innerHTML=`<section class="play-shell"><button class="back" data-map>← Quest map</button><div class="challenge-head"><small>${quests[state.level].chapter.toUpperCase()} · ${quests[state.level].reference}</small><h1>${title}</h1><p>${instructions}</p></div><div class="challenge" id="challenge">${content}</div></section>`}
function initCreation(){state.round={next:0,options:shuffle(creation.map((_,i)=>i))};renderCreation()}
function renderCreation(){const r=state.round;frame('Put the days in order',`Tap what God made on day ${r.next+1}.`, `<div class="day-track">${creation.map((x,i)=>`<span class="day ${i<r.next?'done':''}">${i<r.next?x[1]:i+1}</span>`).join('')}</div><div class="creation-grid">${r.options.filter(i=>i>=0).map(i=>`<button data-creation="${i}"><span>${creation[i][1]}</span>${creation[i][0]}</button>`).join('')}</div><p class="hint">Read Genesis 1 for the whole story.</p>`)}
function chooseCreation(i){const r=state.round;if(i!==r.next){message('Try another day. Look for what comes next in Genesis 1.');tone(220);return}r.options[r.options.indexOf(i)]=-1;r.next++;tone(660);if(r.next===6)return win('God created the world and called His work good. Every person is made in His image.','Genesis 1:27, 31');renderCreation()}
function initPairs(){const cards=shuffle(animalIcons.flatMap((icon,i)=>[{icon,id:i},{icon,id:i}]));state.round={cards,open:[],found:[],moves:0,busy:false};renderPairs()}
function renderPairs(){const r=state.round;frame('Find the animal pairs',`${r.found.length} of 6 pairs found · ${r.moves} turns`, `<div class="pairs-grid">${r.cards.map((card,i)=>`<button data-card="${i}" class="pair ${r.open.includes(i)||r.found.includes(card.id)?'flipped':''}" ${r.found.includes(card.id)?'disabled':''} aria-label="${r.open.includes(i)||r.found.includes(card.id)?card.icon:'Hidden animal'}">${r.open.includes(i)||r.found.includes(card.id)?card.icon:'?'}</button>`).join('')}</div><p class="hint">Tap two cards. Remember where each animal is hiding.</p>`)}
function chooseCard(i){const r=state.round;if(r.busy||r.open.includes(i)||r.found.includes(r.cards[i].id))return;r.open.push(i);tone(450);renderPairs();if(r.open.length===2){r.moves++;const[a,b]=r.open;if(r.cards[a].id===r.cards[b].id){r.found.push(r.cards[a].id);r.open=[];tone(720);if(r.found.length===6)return setTimeout(()=>win('God cared for Noah and the living creatures through the flood.','Genesis 8:1'),450);renderPairs()}else{r.busy=true;rainbowTimers.push(setTimeout(()=>{r.open=[];r.busy=false;renderPairs()},800))}}}
function initRainbow(){state.round={pattern:Array.from({length:4},()=>Math.floor(Math.random()*colors.length)),entered:[],showing:true,lit:-1};renderRainbow();playPattern()}
function renderRainbow(){const r=state.round;frame('Remember the colors',r.showing?'Watch the pattern...':`Repeat the pattern: ${r.entered.length} of ${r.pattern.length} colors`, `<div class="rainbow-progress">${r.pattern.map((_,i)=>`<span class="${i<r.entered.length?'done':''}"></span>`).join('')}</div><div class="color-grid">${colors.map(([name,color],i)=>`<button class="color-tile ${r.lit===i?'lit':''}" style="--tile:${color}" data-color="${i}" aria-label="${name}" ${r.showing?'disabled':''}>${name}</button>`).join('')}</div><button class="secondary" data-replay ${r.showing?'disabled':''}>Watch again</button>`)}
function playPattern(){const r=state.round;r.showing=true;r.entered=[];r.lit=-1;renderRainbow();r.pattern.forEach((n,i)=>{rainbowTimers.push(setTimeout(()=>{r.lit=n;renderRainbow();tone(330+n*85)},650+i*750));rainbowTimers.push(setTimeout(()=>{r.lit=-1;renderRainbow()},1120+i*750))});rainbowTimers.push(setTimeout(()=>{r.showing=false;renderRainbow()},650+r.pattern.length*750))}
function chooseColor(i){const r=state.round;if(r.showing)return;if(i!==r.pattern[r.entered.length]){message('Try again. Watch the colors once more.');tone(220);playPattern();return}r.entered.push(i);tone(500+i*75);if(r.entered.length===r.pattern.length)return win('God set the rainbow as a sign of His covenant. He remembers His promise.','Genesis 9:13–16');renderRainbow()}
function initSling(){state.round={hits:0,throws:0,position:0,last:performance.now(),direction:1};renderSling();animateSling()}
function renderSling(){const r=state.round;frame('Time the sling',`Land 2 good throws. ${r.hits} hits · ${r.throws} throws`, `<div class="sling-scene"><div class="sling-track"><div class="hit-zone"></div><div id="marker" class="marker" style="left:${r.position}%"></div></div><span class="zone-label">AIM FOR THE CENTER</span></div><button class="primary throw" data-throw>Release the stone ✦</button><p class="hint">The marker keeps moving. You can try as often as you need.</p>`)}
function animateSling(){if(state.view!=='play'||quests[state.level].kind!=='sling')return;const r=state.round;r.position=50+49*Math.sin((performance.now()-r.last)/730);const marker=$('#marker');if(marker)marker.style.left=r.position+'%';slingTimer=requestAnimationFrame(animateSling)}
function throwStone(){const r=state.round;r.throws++;const hit=Math.abs(r.position-50)<17;if(hit){r.hits++;tone(740);message('Good timing!')}else{tone(230);message('Close! Watch the center and try again.')}if(r.hits>=2)return win('David said the battle belonged to the Lord. His courage rested in God, not in his own strength.','1 Samuel 17:47');renderSling()}
const maze=[0,0,1,0,0,0, 1,0,1,0,1,0, 0,0,0,0,1,0, 0,1,1,0,0,0, 0,0,0,1,1,0, 0,1,0,0,0,0];
function initSheep(){state.round={position:0,steps:0};renderSheep()}
function renderSheep(){const r=state.round;frame('Find the lost sheep',`Move the shepherd through the open path. ${r.steps} steps`, `<div class="maze">${maze.map((wall,i)=>`<button data-cell="${i}" class="maze-cell ${wall?'wall':''} ${i===r.position?'player':''} ${i===35?'goal':''}" aria-label="${i===r.position?'Shepherd':i===35?'Lost sheep':wall?'Rocky hill':'Open path'}" ${wall?'disabled':''}>${i===r.position?'🧑‍🌾':i===35?'🐑':wall?'':'·'}</button>`).join('')}</div><p class="hint">Tap a neighboring square to move. You can also use arrow keys.</p>`)}
function moveSheep(i){const r=state.round,p=r.position;if(maze[i]||!(Math.abs(i-p)===6||Math.floor(i/6)===Math.floor(p/6)&&Math.abs(i-p)===1)){message('Choose a neighboring open square.');return}r.position=i;r.steps++;tone(450);if(i===35)return win('Jesus told of a shepherd who searched for the one that was lost. He welcomes us with joy.','Luke 15:4–7');renderSheep()}
function win(truth,reference){stopActivity();const i=state.level;state.best[i]=true;state.unlocked=Math.max(state.unlocked,Math.min(quests.length,i+1));save();state.view='won';header();$('#app').innerHTML=`<section class="win"><span class="win-icon">${quests[i].icon}</span><span class="eyebrow">QUEST COMPLETE</span><h1>${quests[i].title}</h1><p>${truth}</p><strong>${reference}</strong><div class="win-actions"><button class="primary" data-next>${i<quests.length-1?'Next quest →':'Return to quest map →'}</button><button class="secondary" data-replay-level>Play again</button></div><div class="grace-note"><b>God’s love is not a prize.</b> Jesus died and rose again to save sinners. We receive His grace through faith, not by finishing levels. <span>Ephesians 2:8–9 · 1 Corinthians 15:3–4</span></div></section>`;tone(880)}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.id==='home'||b.hasAttribute('data-map'))return showMap();if(b.id==='sound'){state.sound=!state.sound;header();return}if(b.dataset.level!==undefined)return startLevel(Number(b.dataset.level));if(b.hasAttribute('data-begin'))return begin();if(b.dataset.creation!==undefined)return chooseCreation(Number(b.dataset.creation));if(b.dataset.card!==undefined)return chooseCard(Number(b.dataset.card));if(b.dataset.color!==undefined)return chooseColor(Number(b.dataset.color));if(b.hasAttribute('data-replay'))return playPattern();if(b.hasAttribute('data-throw'))return throwStone();if(b.dataset.cell!==undefined)return moveSheep(Number(b.dataset.cell));if(b.hasAttribute('data-next'))return state.level<quests.length-1?startLevel(state.level+1):showMap();if(b.hasAttribute('data-replay-level'))return startLevel(state.level)});
document.addEventListener('keydown',e=>{if(state.view!=='play'||quests[state.level].kind!=='sheep')return;const d={ArrowUp:-6,ArrowDown:6,ArrowLeft:-1,ArrowRight:1}[e.key];if(!d)return;e.preventDefault();const i=state.round.position+d;if(i>=0&&i<36)moveSheep(i)});
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'open_bible_quest',title:'Open a Bible Quest',description:'Open an unlocked Bible story challenge in the visible game.',inputSchema:{type:'object',properties:{quest:{type:'integer',minimum:1,maximum:5}},required:['quest'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){const n=input?.quest;if(!Number.isInteger(n)||n<1||n>5||n-1>state.unlocked)throw Error('Quest is not unlocked.');startLevel(n-1);return{opened:quests[n-1].title}}})).catch(()=>{})}catch{}}
showMap();
